#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
PROTECTED_BRANCHES="^(main|develop)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo "🚫 Cannot push to remote $BRANCH branch."
  exit 1
fi
